### ISSUE TITLE
Add files to be watched

### ISSUE THREAD

**Issue by bmaupin** [privatenumber/tsx#181]
### Feature request

I would like to be able to add files to be watched in addition to the default, for example to watch the `.env` file.

### Why?

I use a `.env` file with `dotenv` for environment variables. Often I'll change a value in `.env` during runtime to test something (e.g. enable/disable feature flag). 

With nodemon I'm using:

```
nodemon --watch src --watch .env src/index.ts
```

It would be nice to be able to do this with tsx as well.

### Alternatives

My current alternative is nodemon+ts-node+swc. But tsx seems like a more convenient all-in-one solution.

**Comment by clearly-outsane** [comment]
Any ideas on how to add this? I can help

**Comment by privatenumber** [comment]
This issue is now resolved in [v4.18.0](https://github.com/privatenumber/tsx/releases/tag/v4.18.0).

If you're able to, [your sponsorship](https://github.com/sponsors/privatenumber) would be very much appreciated.
