### ISSUE TITLE
Add logging to watch function for easier troubleshooting

### ISSUE THREAD

**Issue by Amorites** [privatenumber/tsx#218]
### Feature request

It would be helpful to have more detailed logging when using the watch function in TSX. Specifically, it would be beneficial to log the specific event and path that caused a change, making it easier to troubleshoot issues. This would greatly reduce the time and effort required to identify and resolve problems.

### Why?

While working with TSX in conjunction with Vite SSR, I have encountered an issue where Vite generates intermediate files during startup, causing unnecessary reruns that have caused me to spend a significant amount of time troubleshooting. Despite attempts to add logging to the TSX rerun function, I have found that the log function returns "undefined". I eventually discovered that the `debounce` process was discarding all parameters, leading to this issue.

This issue has caused significant disruptions to my workflow, as it has made it difficult to identify and resolve issues efficiently. It would be beneficial to provide a solution for this problem, such as modifying the debounce process or providing a workaround for the logging issue.

**Comment by mattfysh** [comment]
I'm also having trouble getting watch to work and manually added some log lines to dist/cli.js

Specifically I can see a whole bunch of node_modules files in the .on('message') callback, but nothing from my local project dir. As a result, watch will only rerun if I update the entry file, but does not rerun for all other files

I'm not sure why my other files don't come through from `runProcess.on('message')` but I've had to revert to nodemon for the time being: https://github.com/esbuild-kit/tsx/blob/64ece39ea4ecda6b103901b0fbb39799d217dce3/src/watch/index.ts#L86

**Comment by privatenumber** [comment]
If you think there's a bug, would you mind filing a bug report with a repro?

**Comment by karlhorky** [comment]
@privatenumber Nice, thanks for #412! I'll test it with my failure case when it's released (potentially in `4.5.0`)

**Comment by karlhorky** [comment]
Ok, looking at the logs with [`tsx@4.5.0`](https://github.com/privatenumber/tsx/releases/tag/v4.5.0), I see that it's listening to the compiled files in the `.next` folder, which I imagined would have been ignored because [hidden `.*` directories are ignored by default](https://github.com/privatenumber/tsx#:~:text=All%20imported%20files%20are%20watched%20except%20from%20the%20following%20directories%3A%20node_modules%2C%20bower_components%2C%20vendor%2C%20dist%2C%20and%20.*%20(hidden%20directories).) (but maybe they are not ignored when they are part of a path in another folder).

```
GET /_next/static/webpack/a67d1f9a228e97fd.webpack.hot-update.json 200 143.315 ms - 44
GET /_next/static/webpack/webpack.a67d1f9a228e97fd.hot-update.js 200 11.379 ms - 858
4:41:50 PM [tsx] change in ./../website/.next/server/app/(dashboard)/page_client-reference-manifest.js Restarting...
4:41:55 PM [tsx] unlink in ./../website/.next/server/app/cohorts/[cohortSlug]/page_client-reference-manifest.js Restarting...
Listening at http://localhost:3000
 ✓ Compiled /middleware in 220ms (62 modules)
 ○ Compiling / ...
4:42:01 PM [tsx] add in ./../website/.next/server/vendor-chunks/combined-stream.js Restarting...
4:42:05 PM [tsx] unlink in ./../website/.next/server/app/(dashboard)/page.js Restarting...
```

I'll try to find a way to ignore these files.

**Comment by karlhorky** [comment]
Ok, I think I found a way to ignore the files, but this configuration unfortunately also causes `ERR_MODULE_NOT_FOUND` errors for anything inside of `.next`... 🤔

```bash
$ pwd
~/p/project/packages/server
$ pnpm tsx watch --clear-screen=false --ignore ./../website/.next/**/* index.ts

...

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '~/p/project/packages/website/.next/cache/webpack' imported from ~/p/project/packages/server/
```

**Comment by karlhorky** [comment]
If it's not my error but rather a bug, happy to open a new issue with a more structured bug report. 👍

**Comment by privatenumber** [comment]
Sounds like unexpected behavior that was surfaced as a result of this feature. Except for your second log; are you saying adding the `--ignore ./../website/.next/**/*` actually causes a runtime error?

Since this isn't actually relevant to this Issue topic, would you mind filing a bug?
