### ISSUE TITLE
SIGINT handler doesn't wait for child proc to close, but instead kills it immediately

### ISSUE THREAD

**Issue by NinjaInShade** [privatenumber/tsx#253]
#### What did you do? (Provide reproduction code in next section)
  
  I have a SIGINT handler that does some disposing and when running with TSX in watch mode, and SIGINT is received, it never waits for the child process to actually close, it just kills it immediately.

  #### What did you expect to happen?
  
  To let SIGINT handler function to fully run and exit if event loop empty or if the handler function calls process.exit().

  #### What happened instead?
  
  It doesn't wait, it just kills the child process immediately, so dispose code never runs fully.

If I comment out line 130 in `src/watch/index.ts` *some*/*more* dispose code runs, but definitely isn't waiting for event loop to finish or process.exit() to be called

  #### Do you have an error stack-trace or screenshots?

  Nothing to report in terms of "errors" here.

### Reproduction

You can see this with this example code:
```
import http from 'node:http';

const server = http.createServer();
server.listen(5605);

process.on('SIGINT', async () => {
    console.log('Got SIGINT');

   setTimeout(() => {
      console.log('finished');
   }, 3000);
});
```

And then run this file with `tsx file.ts` and trigger a SIGINT through typing `Ctrl-C` in the terminal.

If you ran this with just `node` - provided you change it to plain javascript, no typescript extension - it would wait to dispose properly

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 7700X 8-Core Processor
    Memory: 1018.85 MB / 31.15 GB
  Binaries:
    Node: 19.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by midzelis** [comment]
My latest commit [7467d2f](https://github.com/esbuild-kit/tsx/pull/254/commits/7467d2f264d8dfac08e48b67b728f9b6e2728162) improves/fixes your use case. 

I also needed to modify your example like so

```js
import http from 'node:http';

const server = http.createServer();
server.listen(5605);

process.on('SIGINT', async () => {
    console.log('Got SIGINT');

   setTimeout(() => {
      console.log('finished');
      server.close();
      process.removeAllListeners()
   }, 3000);
});
process.on('SIGTERM', async () => {
    console.log('Got SIGTERM');

   setTimeout(() => {
      console.log('finished');
      server.close();
      process.removeAllListeners()
   }, 1000); // <— adjust this timeout to see how the new watcher behaves
});

console.log("Starting");
```
In that commit, the watcher will wait up to 5s before force-killing the process. Your process will have 5 seconds to do a graceful cleanup. 

Additionally, pressing <enter/return> will not cause the process to be SIGTERM'd like before. This means you can watch processes that do I/O from the command line. 

If the child process exists, you can press <enter/return> to rerun, or ctrl-c to quit the watcher.

**Comment by endel** [comment]
Would love to see signals fixed!

**Comment by privatenumber** [comment]
This was fixed via https://github.com/privatenumber/tsx/pull/395

Also, as of https://github.com/privatenumber/tsx/pull/412, watch mode will allow 5s of cleanup before force killing on reload, and 1s when exiting (Ctrl+C).

**Comment by EloB** [comment]
@privatenumber Is it possible to change that 5 seconds? Through cli?

**Comment by privatenumber** [comment]
@EloB can you file a feature request?
I'm not sure if I understand your use case and I'd like to learn more.

This issue is resolved and closed so I'll be locking it to prevent messages from being missed.
