### ISSUE TITLE
Webpack support for tsx

### ISSUE THREAD

**Issue by fregante** [privatenumber/tsx#278]
### Feature request

This isn't a feature request for `tsx`, but a call to support `tsx` in webpack. I opened a couple of issues upstream in hope of this become a reality:

- https://togithub.com/webpack/webpack/issues/17553
- https://togithub.com/gulpjs/interpret/issues/95

### Why?

Less config is best. Webpack already supports a number of loaders natively, so supporting `tsx` might not require much more work.

### Alternatives

mo' config, mo' problems:
```
cross-env NODE_OPTIONS="--loader tsx --no-warnings=ExperimentalWarning" webpack --mode=production
```

**Comment by privatenumber** [comment]
Appreciate the issue and letting me know you opened issues upstream, thank you! Hope Webpack adopts tsx!

I'm going to close this out as there doesn't seem to be anything actionable on tsx's end
