### ISSUE TITLE
perf: openapi-zod-client runs slow

### ISSUE THREAD

**Issue by imballinst** [privatenumber/tsx#285]
### Problem

Hello! First time user here, so apologies if I am not 100% aware of what is supported and what is not.

I came from ts-node and esbuild-register which both have issues with ESM, tsconfig paths, and all that, until I found this library.

It's really nice to have something just works out of the box, but then I faced this weird case where if I import this package called `openapi-zod-client`. Basically what this package does is converting an OpenAPI specification into generated TypeScript files.

Somehow, if I use any imports from that package, the script just won't run. In my GitHub Codespaces machine, it's running for like 8 seconds without output. However, in StackBlitz, it just runs forever (not sure why).

### Expected behavior

The expected behavior is `tsx` is able to run the script containing any kind of package normally (without hanging or some sort of that), as long as the package exists in the repository.

### URL

https://stackblitz.com/edit/vitejs-vite-w3f9xb?file=package.json,index.ts&terminal=dev

### Version

3.12.7

### Node.js version

16.20.0

### Package manager

npm

### Operating system

Linux

### It would be amazing if you can contribute to the project!

- [ ] I plan to open a pull request for this issue.

**Comment by privatenumber** [comment]
Do you mind making your reproduction minimal? There seems to be a lot of irrelevant concerns.

**Comment by imballinst** [comment]
oh right, apologies! I just tried to clean it up, hopefully this makes it less cluttered? `test.ts` should be the thing that I want to highlight.

![Untitled](https://github.com/esbuild-kit/tsx/assets/7077157/f4ee48dc-d020-47f0-a70f-8f4bd39f83d1)

**Comment by privatenumber** [comment]
Is everything in `api.json` necessary?

**Comment by imballinst** [comment]
Now that you mentioned it, I think it's not necessary. I've cut it down to this now (so only `test.ts` is left):

```ts
import { generateZodClientFromOpenAPI } from 'openapi-zod-client';
import * as path from 'path';

async function run() {
  console.info('hello world');
  // When the thing below is disabled, it will print the hello above
  // Otherwise, it won't
  await generateZodClientFromOpenAPI({
    openApiDoc: {
      openapi: '3.0.2',
      info: {
        title: 'test',
        version: '',
      },
      paths: {},
    },
    distPath: path.join(process.cwd(), 'scripts/dist'),
  });
}

run();
```

Let me know what you think, thanks!

**Comment by privatenumber** [comment]
After optimizing transformations so it only happens on ESM code, this still appeared kinda slow and it turned out it's actually happening on Node.js side when `process.setSourceMapsEnabled(true)` is invoked. In this case, the dependencies has a lot of sourcemaps that Node.js is now parsing.

Will look into optimizing this further.

**Comment by privatenumber** [comment]
In the next major release, tsx will run almost as fast in Node.js v20 (v18 has limitations with the source map that we can't work around).

**Comment by imballinst** [comment]
> In this case, the dependencies has a lot of sourcemaps that Node.js is now parsing.

I see, TIL that was the root cause. Cool!

> In the next major release, tsx will run almost as fast in Node.js v20 (v18 has limitations with the source map that we can't work around).

That's awesome, I think I'm fine with the Node.js v20 condition. Thanks for the explanation and working on this issue! 🙇‍♂️

**Comment by privatenumber** [comment]
Not the root cause, but it's one of the issues.

Just released https://github.com/privatenumber/tsx/releases/tag/v4.0.0, which should address this issue.

Hope it's a lot better for you!

**Comment by imballinst** [comment]
I just tried it in [StackBlitz](https://stackblitz.com/edit/vitejs-vite-box2ml?file=package.json,index.ts&terminal=dev) using the latest major, and it seems to be running well. Thanks a lot for working on this, really appreciate it!
