### ISSUE TITLE
.js extensions not resolved to .ts file in exports map

### ISSUE THREAD

**Issue by SettingDust** [privatenumber/tsx#341]
https://github.com/esbuild-kit/tsx/issues/342
After looked into it. It seems not relate to the issue. So, open new one here
Repo: https://github.com/SettingDust/esbuild-esm-loader-exports-map-ts

**Comment by privatenumber** [comment]
There's no bug description and I can't access the reproduction repository so I'm closing.

Happy to re-open if details and reproduction are provided.

**Comment by SettingDust** [comment]
Haven't noticed it's private. Make it public now

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.14.0

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
