### ISSUE TITLE
Are "paths" in tsconfig expected to be respected?

### ISSUE THREAD

**Issue by neongreen** [privatenumber/tsx#343]

**Comment by privatenumber** [comment]
Just took a look.

It's not working because you're using the [esm-loader](https://github.com/esbuild-kit/esm-loader) in a CommonJS package. Instead, you should've used the [cjs-loader](https://github.com/esbuild-kit/cjs-loader).

Now, you can just use tsx:
```
tsx tools/golden-games.ts
```

Closing as there's no tsx bug here.
