### ISSUE TITLE
`ERR_UNSUPPORTED_ESM_URL_SCHEME`  when dyanmic import in windows

### ISSUE THREAD

**Issue by tangdaoyuan** [privatenumber/tsx#345]
### Description

In windows, Using dynamic import with absolute path cause `ERR_UNSUPPORTED_ESM_URL_SCHEME` error

![image](https://user-images.githubusercontent.com/8007202/191320171-f0e19191-d6c8-4cb7-80e1-d15c15fb348c.png)

### Reproduction

1. create a.ts file  following
```ts
import path from "path";

const abs_path = path.resolve('./b.ts', );  // absolute path
import(abs_path)
```

2. run  `node --loader @esbuild-kit/esm-loader a.ts`

### extra

`tsx`  has same error.

**Comment by 5icoder** [comment]
The same error in tsx@4.6.1

![image](https://github.com/privatenumber/tsx/assets/49341227/3c0431d5-7697-43e3-b4b3-2e657f2ce504)

tsx@4.6.1
node@v18.17.1
pnpm@8.10.0
typescript@5.3.2

**Comment by TimPietrusky** [comment]
I ran into the same issue, but I got it working when using not an absolute path, but a relative path as configured in the `path` of tsconfig:

**`tsconfig`**

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
}
```

**dynamic import**
```ts
const name = "mydynamicimport";

await import(`@/${name}`);
```

While the file that I want to import exists at `src/mydynamicimport.ts`

So the "issue" here is the usage of an absolute path, which is not working on Windows. You would have to use a proper URL:

```ts
import path from "node:path";
import { pathToFileURL } from "node:url";

export async function dynamicImport(fullPath: string) {
	const fileURL = pathToFileURL(fullPath).href;
	return import(fileURL);
}

// Usage example, assuming your mycustomfile.ts is inside of "src"
await dynamicImport(path.join(process.cwd(), "src", "mycustomfile"));
```

This will produce an URL like this: `file:///D:/src/mycustomfile`.

**Comment by so1ve** [comment]
It works when dynamic importing a literal:

`import('file:///D:/foo.ts')` works

**Comment by so1ve** [comment]
Is https://github.com/esbuild-kit/esm-loader/pull/39 a proper fix? I'd like to back-port it to tsx if it works.

**Comment by m-kawahara** [comment]
Thank you for your wonderful library.
I am Japanese. This is my first comment in English. I am sorry if there is any strange English.

I am developing on windows, and I had this issue problem when I specified the absolute path.
I think maybe the following logic is reversed.
https://github.com/privatenumber/tsx/blob/50d81944b1a2ced81f0c4a575f18df340d56ec38/src/esm/loaders.ts#L269

**Comment by privatenumber** [comment]
I'm currently wondering if this is even a tsx issue, or if this is a Node.js issue ya'll are trying to patch with tsx?

Specifically, does this work in Node (no tsx) on Windows?
```js
import path from "path"

const abs_path = path.resolve('./b.ts', );  // absolute path
import(abs_path)
```

To determine this, I'd throw the above snippet in a GitHub repo with CI on ubuntu and windows running it.

**Comment by geisterfurz007** [comment]
@privatenumber very much appears to be a Node issue itself

![grafik](https://github.com/privatenumber/tsx/assets/26303198/d728d41b-a2f2-4e68-923c-4b3ca99a6a7b)

**Comment by privatenumber** [comment]
Thanks for verifying @geisterfurz007 

Closing as it's expected behavior.
