### ISSUE TITLE
Custom ESM karma server breaks with tsx

### ISSUE THREAD

**Issue by Lodin** [privatenumber/tsx#346]
### Bug description

I have a project that runs a custom Karma server. It is custom because I want to use ESM for Karma while it supports only CJS by default. However, if I try to run it with `tsx` (command is `tsx karma.config.ts`), the server fails with the following error: 
```
07 11 2022 16:25:58.760:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "proxies"! (Resolving: webServer -> proxies)
<root>\node_modules\di\lib\injector.js:22
    return new Error(stack ? msg + ' (Resolving: ' + stack + ')' : msg);
           ^

Error: No provider for "proxies"! (Resolving: webServer -> proxies)
    at error (<root>\node_modules\di\lib\injector.js:22:12)
    at Object.get (<root>\node_modules\di\lib\injector.js:9:13)
    at get (<root>\node_modules\di\lib\injector.js:54:19)
    at <anonymous> (<root>\node_modules\di\lib\injector.js:71:14)
    at Array.map (<anonymous>)
    at Object.invoke (<root>\node_modules\di\lib\injector.js:70:31)
    at createWebServer (<root>\node_modules\karma\lib\web-server.js:65:44)
    at Array.invoke (<root>\node_modules\di\lib\injector.js:75:15)
    at Object.get (<root>\node_modules\di\lib\injector.js:48:41)
    at Server._close (<root>\node_modules\karma\lib\server.js:438:38)
```
However, it works correctly if I use `node --loader @esbuild-kit/esm-loader karma.config.ts` instead, it works as expected.

Also, I noticed that if I use two loaders (for ESM and CJS) at the same time (command `node --loader @esbuild-kit/esm-loader -r @esbuild-kit/cjs-loader karma.config.ts`), it also fails with the same error.

### Reproduction

1. Clone [this](https://github.com/Lodin/karma-tsx-issue) repo.
2. `npm install`
3. `npm run test`

### Environment

```shell
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 22.32 GB / 47.71 GB
  Binaries:
    Node: 19.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    tsx: ^3.11.0 => 3.11.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Fixed in https://github.com/privatenumber/tsx/releases/tag/v4.0.0 by optimizing compilation to be more selective

Thanks for your issue and hope it works well for you!
