### ISSUE TITLE
Error uv_os_get_passwd returned ENOENT when updating to v3.14.0

### ISSUE THREAD

**Issue by ST-DDT** [privatenumber/tsx#352]
### Problem

Potentially this change https://github.com/esbuild-kit/tsx/commit/7e916f5a1db5b21589cedc1dc91b0c498f87adf9 caused the following issue

````txt
node:os:365
    throw new ERR_SYSTEM_ERROR(ctx);
    ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at new SystemError (node:internal/errors:256:5)
    at new NodeError (node:internal/errors:367:7)
    at Object.userInfo (node:os:365:11)
    at <instance_members_initializer> (/__w/faker/faker/node_modules/.pnpm/tsx@3.14.0/node_modules/tsx/dist/index-5f60304b.cjs:21:492)
    at new pA (/__w/faker/faker/node_modules/.pnpm/tsx@3.14.0/node_modules/tsx/dist/index-5f60304b.cjs:21:578)
    at Object.<anonymous> (/__w/faker/faker/node_modules/.pnpm/tsx@3.14.0/node_modules/tsx/dist/index-5f60304b.cjs:21:1813)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -2,
    code: 'ENOENT',
    message: 'no such file or directory',
    syscall: 'uv_os_get_passwd'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

Node.js v20.6.1
 ELIFECYCLE  Command failed with exit code 1.
````

https://github.com/faker-js/faker/actions/runs/6611943169/job/17956808484?pr=2501
https://github.com/esbuild-kit/tsx/blob/7e916f5a1db5b21589cedc1dc91b0c498f87adf9/src/utils/transform/cache.ts#L27

Sadly I'm unable to reproduce it locally, it only happens reproducibly in a specific GitHub CI potentially linked to either a custom image or an explicit user.

https://github.com/faker-js/faker/blob/e901641580e8718656425dc68e774e0557f62d17/.github/workflows/ci.yml#L119-L122

### Expected behavior

The error should not be thrown. It works perfectly in v3.13.0.

### Minimal reproduction URL

https://github.com/faker-js/faker/pull/2501

### Version

v3.14.0

### Node.js version

v20.6.1

### Package manager

pnpm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by ST-DDT** [comment]
Since this only happens in CI it might be safe to omit the user id from the temp folder.

**Comment by ST-DDT** [comment]
https://github.com/esbuild-kit/tsx/pull/332

**Comment by privatenumber** [comment]
PR welcome to replace `os.userInfo().uid` with `process.geteuid()`:
https://nodejs.org/api/process.html#processgeteuid

**Comment by ST-DDT** [comment]
> PR welcome to replace `os.userInfo().uid` with `process.geteuid()`: [nodejs.org/api/process.html#processgeteuid](https://nodejs.org/api/process.html#processgeteuid)

I will create a PR soon.

**Comment by ST-DDT** [comment]
PR created: https://github.com/esbuild-kit/tsx/pull/355

- https://github.com/esbuild-kit/tsx/pull/355

**Comment by kaiyoma** [comment]
I think I am running into this problem as well. I reported it here (https://github.com/esbuild-kit/tsx/issues/363) and offered to help but the author is being very combative for some reason.

I am also seeing this problem in a Linux CI environment and I'm also seeing the issue with 3.14.0. I also cannot reproduce locally (only in CI).

In my case, I don't get any error output, which would be useful. Instead, there's no output at all and then the CI pipeline fails.

**Comment by raulfdm** [comment]
Can someone check if on v4 this problem still happens?

**Comment by privatenumber** [comment]
v4 doesn't include any fixes for this

**Comment by ST-DDT** [comment]
PR created: #376 

- #376
