### ISSUE TITLE
Support `--cwd` parameter like `ts-node`

### ISSUE THREAD

**Issue by wottpal** [privatenumber/tsx#387]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and will not support arbitrary Node.js enhancements

### Feature request

A parameter to set the working directory of the `tsx` command like in `ts-node` (https://typestrong.org/ts-node/docs/options/#cwd).

![CleanShot 2023-11-14 at 14 02 20@2x](https://github.com/privatenumber/tsx/assets/3930150/1004bc76-407f-4ce5-b0f4-ed5893b76e82)

### Motivations

In my current project, I have all `*.ts` up for execution in a subdirectory (e.g. `src/`). I want to create a shorthand script that allows for easy execution of all of those w/o specifying the directory, e.g. `npm run script file.ts` instead of `npm run script src/file.ts`.

Script could be defined as (this works with `ts-node`):

```
"script": "tsx --cwd=src"
```

### Alternatives

* Supply the working directory as an environment variable.
* Ugly/verbose workaround script: 

```
"script": "f() { tsx ./src/$1; }; f \"$@\""
```

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
> - [x]  I understand tsx aims for TypeScript parity and will not support arbitrary Node.js enhancements *

I think this feature fits in the "arbitrary Node.js enhancements" category. Consider making this request upstream to Node.js.
