### ISSUE TITLE
SIGINT has no effect if tsx is running an infinite loop

### ISSUE THREAD

**Issue by sadkebab** [privatenumber/tsx#394]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

### Problem

You have a file called `file.ts` with an infinite loop in it like `while(true){}`.
By running `tsx file.ts` you won't be able to stop the execution of tsx by sending a SIGINT (for example with CTRL+C) and the process will run indefinitely until it receives another signal like a SIGQUIT or a SIGSTOP.

### Expected behavior

tsx should stop the execution after the SIGINT.

### Minimal reproduction URL

https://stackblitz.com/edit/node-fc7ukf?file=index.ts

### Version

v4.1.3

### Node.js version

v20.7.0

### Package manager

pnpm

### Operating system

macOS

### Contributions

- [x] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by sadkebab** [comment]
The main issue that this problem created to me was that, by defining a script in a package.json like 
`"scripts": {
 "test": "tsx file.ts"
 }` where `file.ts` would run an infinite loop, after executing it with `pnpm test` if I sent a couple of SIGINT by keyboard shortcut the script would quit... but the child process spawned by tsx was still running in the background, eating 100% cpu and draining the battery of my laptop.

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.4.0

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
