### ISSUE TITLE
prevent initial clear-screen when --clear-screen=false

### ISSUE THREAD

**Issue by odama626** [privatenumber/tsx#396]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and will not support arbitrary Node.js enhancements

### Feature request

prevent initial clear screen when clear-screen=false

### Motivations

running this for a package in a turborepo package, and it is clearing the terminal in watch mode with --clear-screen=false when first run.

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by odama626** [comment]
after digging into the code, I'm not convinced this is caused by tsx

**Comment by privatenumber** [comment]
Please do not try to circumvent the bug report form by filing a feature request.

A minimal reproduction is necessary to prevent people from filing issues without doing their due diligence.
