### ISSUE TITLE
Support import attributes via esbuild v0.19.7 upgrade

### ISSUE THREAD

**Issue by SuperchupuDev** [privatenumber/tsx#408]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and will not support arbitrary Node.js enhancements

### Feature request

TypeScript 5.3 was just released, and it added support for import atrributes: `import 'thing.json'  with { type: 'json' }`. Node 21 and 20.10.0 added support for this as well. esbuild just added support too, and updating it to [`0.19.7`](https://github.com/evanw/esbuild/releases/tag/v0.19.7) could probably close this issue altogether

### Motivations

The previous syntax, that uses the `assert` keyword, is now deprecated. Adding support for the new syntax in tsx would help adoption

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
We can't upgrade esbuild to 0.19.x until this is fixed:
https://github.com/evanw/esbuild/issues/3353

**Comment by privatenumber** [comment]
https://github.com/evanw/esbuild/issues/3353 has been fixed.

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.7.0

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
