### ISSUE TITLE
`tsx` doesn't work on Node 18.19

### ISSUE THREAD

**Issue by brc-dd** [privatenumber/tsx#421]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

### Problem

Unable to run `tsx` on Node 18:

```
❯ pnpm tsx ./foo.ts         

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
    at Q (file:///Users/divyansh/foo/node_modules/.pnpm/tsx@4.6.0/node_modules/tsx/dist/esm/index.mjs:1:1793)
    at Hooks.addCustomLoader (node:internal/modules/esm/hooks:202:24)
    at Hooks.register (node:internal/modules/esm/hooks:168:16)
    at async initializeHooks (node:internal/modules/esm/utils:167:5)
    at async customizedModuleWorker (node:internal/modules/esm/worker:104:24)

Node.js v18.19.0
```

Working fine till Node v18.18 (https://nodejs.org/en/blog/release/v18.19.0#esm-and-customization-hook-changes)

### Minimal reproduction

```
// foo.ts:

console.log('hello')

// on terminal:

nvm use 18
pnpm add -D tsx
pnpm tsx ./foo.ts
```

### Expected behavior

Not fail on LTS versions.

### Version

v4.6.0

### Node.js version

v18.19.0

### Package manager

pnpm

### Operating system

macOS

### Contributions

- [x] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.6.1

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
