### ISSUE TITLE
Using with mocha and NodeJS v19.9.0 causes "F.register is not a function" error

### ISSUE THREAD

**Issue by glektarssza** [privatenumber/tsx#428]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

### Problem

Currently I am seeing this issue in the head of one of my projects ([glektarssza/ftb-tool](https://github.com/glektarssza/ftb-tool)). I use [Mocha](https://github.com/mochajs/mocha), optionally with [nyc](https://github.com/istanbuljs/nyc) for coverage, to test my project. This morning I did a `npm upgrade` and now my tests are failing in my local copy but not in the GitHub Actions. Running `npm run test` in my local copy results in the following logs/stack trace.

```
> ftb-tool@0.3.0 test
> mocha


✖ ERROR: TypeError: F.register is not a function
    at $ (file:///Users/989270160/Projects/ftb-tool/node_modules/tsx/dist/esm/index.mjs:1:693)
    at file:///Users/989270160/Projects/ftb-tool/node_modules/tsx/dist/esm/index.mjs:5:1939
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

This issue does not occur on versions of NodeJS later than v19.9.0. I have tested the latest v20 and v21 versions and they appear to be fine.

### Expected behavior

* No error occurs and my unit tests run normally.

### Minimal reproduction URL

https://github.com/glektarssza/tsx-bug-minimal-reproduction

### Version

v4.6.1

### Node.js version

v19.9.0

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by glektarssza** [comment]
Worth noting that the reason I am targeting NodeJS v19 is because it's the most recent version supported by the tool I use to package my code into standalone binaries for various operating systems. I'd be comfortable moving to a newer version of NodeJS but it would not be my preference.

**Comment by glektarssza** [comment]
Updated minimal reproduction. I thought Mocha was part of the issue. Turns out it is not. This happens with NodeJS v19 if you just try to run it in REPL mode with `--import=tsx`.

**Comment by privatenumber** [comment]
tsx doesn't support unmaintained versions of Node. Support for v19 ended 6 months ago: https://endoflife.date/nodejs

I'm closing this but I think this is as easy as being more specific in the support ranges for the `register` feature.

Feel free to open a PR if you'd like this addressed.

**Comment by glektarssza** [comment]
> tsx doesn't support unmaintained versions of Node. Support for v19 ended 6 months ago: https://endoflife.date/nodejs

Totally fair and good to know. I'll probably look into using a different packaging tool, then, that supports newer versions of NodeJS.

> Feel free to open a PR if you'd like this addressed.

I'll see about getting one together this weekend. This tool has been immensely helpful so I think it's only appropriate to make a contribution or two.
