### ISSUE TITLE
There is a compatibility problem under windows

### ISSUE THREAD

**Issue by bosens-China** [privatenumber/tsx#434]
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://github.com/bosens-China/error

### Version

4.6.2

### Node.js version

16.20.2

### Package manager

pnpm

### Operating system

Windows

### Problem & Expected behavior

Under 200 words:
- What happened?
node:internal/process/esm_loader:40
internalBinding('errors').triggerUncaughtException(
^
Error [ERR_MODULE_NOT_FOUND]:  Cannot find module 'C:\project\rdbi-workbench\apps\burn-in-tool\vite' imported from  C:\project\rdbi-workbench\apps\burn-in-tool\
- What did you expect instead?
Normal operation
- Do you have an error stack trace?
at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
at new NodeError (node:internal/errors:405:5)
at finalizeResolution (node:internal/modules/esm/resolve:327:11)
at moduleResolve (node:internal/modules/esm/resolve:980:10)
at defaultResolve (node:internal/modules/esm/resolve:1193:11)
at nextResolve (node:internal/modules/esm/hooks:864:28)
At d (file:///C:/project/rdbi-workbench/node_modules/.pnpm/tsx@4.6.2/node_modules/tsx/dist/esm/index.mjs:5:34)
The at O (file:///C:/project/rdbi-workbench/node_modules/.pnpm/tsx@4.6.2/node_modules/tsx/dist/esm/index.mjs:5:1187)
at nextResolve (node:internal/modules/esm/hooks:864:28)
at Hooks.resolve (node:internal/modules/esm/hooks:302:30)
at handleMessage (node:internal/modules/esm/worker:196:24)
at Immediate.checkForMessages (node:internal/modules/esm/worker:138:28)
at process.processImmediate (node:internal/timers:476:21) {
url: 'file:///C:/project/rdbi-workbench/apps/burn-in-tool/vite',
code: 'ERR_MODULE_NOT_FOUND'
}
- Do you have screenshots?
none

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for your issue!

I don't have a Windows. Do you mind adding a GitHub Action to your reproduction that runs the command on Windows so I can see?

**Comment by bosens-China** [comment]
@privatenumber Of course, I've already written it, and here's a link

https://github.com/bosens-China/error/actions/runs/7165392297/job/19507249815

**Comment by privatenumber** [comment]
I debugged this and narrowed it down to `cross-env` misresolving the binary being passed in (e.g. `vite`).

When you remove it, and use something like [pnpm's shell-emulator](https://www.petermekhaeil.com/til/pnpm-shell-emulator/), it works fine.
