### ISSUE TITLE
Broken SIGINT handling

### ISSUE THREAD

**Issue by zaripych** [privatenumber/tsx#446]
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://stackblitz.com/edit/node-qxscsn?file=index.ts

### Version

v4.7.0

### Node.js version

v18.19.0

### Package manager

pnpm

### Operating system

macOS

### Problem & Expected behavior

Given:
- An app that handles SIGINT to finish something gracefully (ie DB write)
- Users presses Ctrl + C

Expected:
- Job finished is printed

Actual:
- Job finished is not printed

Without tsx everything just works offcourse. 

This was introduced quite recently, I think it might have been this PR https://github.com/privatenumber/tsx/pull/395 that broke it.

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by zaripych** [comment]
Hmm. I think maybe this is due to `pnpm`. When I execute this:

```sh
node ./node_modules/tsx/dist/cli.mjs ./index.ts
```

or this:

```sh
npx tsx ./index.ts
```

it seems to work, but when I do this:

```sh
pnpm tsx ./index.ts
```

it doesn't - feel free to close the issue. I'm just keeping it as FYI.

**Comment by privatenumber** [comment]
I saw you comment in https://github.com/pnpm/pnpm/issues/7374. Referencing it here in case others encounter it.

Closing as it's not a tsx issue.

**Comment by alwyntan** [comment]
Having the same issue here, weirdly enough having pnpm run npx with tsx works. Eg. I've prefixed `npx` to my `dev` script and called `pnpm dev` as a workaround currently. Feels weird that there's an extra process, but at least it lets me test my graceful shutdown code.

```{json}
"scripts": {
   "dev": "npx tsx watch ./index.ts"

  // instead of "tsx watch ./index.ts"
}
```
