### ISSUE TITLE
Manual restart is triggered when typing user's prompt using "prompts" or "inquirer" libraries in watch mode

### ISSUE THREAD

**Issue by roman-sh** [privatenumber/tsx#458]
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://stackblitz.com/edit/node-d2kmmv?file=index.ts

### Version

v4.7.0

### Node.js version

v20.9.0

### Package manager

npm

### Operating system

macOS

### Problem & Expected behavior

Under 200 words:
- What happened?
- What did you expect instead?
- Do you have an error stack trace?
- Do you have documentation links?
- Do you have screenshots?

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Duplicate of https://github.com/privatenumber/tsx/issues/456 and https://github.com/privatenumber/tsx/issues/163
