### ISSUE TITLE
flag to not output the entire script minified when there's an eror

### ISSUE THREAD

**Issue by KraXen72** [privatenumber/tsx#462]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and will not support arbitrary Node.js enhancements
- [X] This request cannot be made to Node.js directly, and is specific to tsx
- [X] I understand this form is not for addressing a bug or seeking help

### Feature request

add a flag, so that when an error occurs, only the error and stacktrace get outputed, not the entire minified file that was ran.

### Motivations

I'm using tsx to run some codegen scripts from the package.json
In the scripts, i sometimes purposely throw errors so the user can fix their files before the codegen can continue
however, in recent tsx version, when there's an error, tsx outputs THE ENTIRE MINIFIED SCRIPT FILE before the error!
see (there's entire 2 pages of js code before it too)  
![image](https://github.com/privatenumber/tsx/assets/21956756/f53e462a-b626-42d4-832c-417954559943)

this is confusing for the user and takes up a ton of space. it would be great to add a flag to disable this behaviour

### Alternatives

-

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by KraXen72** [comment]
i will try to add a reproduction.

**Comment by aleclarson** [comment]
Also seeing this.

**Comment by aleclarson** [comment]
Also seeing this. It happens on Node v21, but doesn't on v19.

**Comment by privatenumber** [comment]
Locking due to inactivity
