### ISSUE TITLE
static import not support in repl

### ISSUE THREAD

**Issue by liudonghua123** [privatenumber/tsx#471]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and will not support arbitrary Node.js enhancements
- [X] This request cannot be made to Node.js directly, and is specific to tsx
- [X] I understand this form is not for addressing a bug or seeking help

### Feature request

I tried to test some pieces of code copied from other source in the repl. But it seems does not support `static import`. I also tested with `ts-node`, it works for this scenario.

```
> tsx
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> import {parse} from 'path';
import { parse } from "path";
^^^^^^

Uncaught:
SyntaxError: Cannot use import statement inside the Node.js REPL, alternatively use dynamic import: const { parse } = await import("path");
>

> ts-node
> import {parse} from 'path'
undefined
> parse
[Function: parse]
>
```

I tested with non-repl environment, it works.

![image](https://github.com/privatenumber/tsx/assets/2276718/72e4c0c5-8168-4070-9668-5f612c9ea0cc)

### Motivations

For testing some code snippets without modification easier in the repl mode.

### Alternatives

n.a.

### Additional context

See also https://github.com/nodejs/node/issues/48084#issuecomment-1928921229.

_No response_

### Contributions

- [X] I plan to open a pull request for this issue
- [x] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
This should not have been checked in the issue template:

>  This request cannot be made to Node.js directly, and is specific to tsx

Closing as this is out of scope from tsx's goals towards TS parity.
