### ISSUE TITLE
Is it possible to catch a build-time error during a dynamic import?

### ISSUE THREAD

**Issue by thelinuxlich** [privatenumber/tsx#472]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and will not support arbitrary Node.js enhancements
- [X] This request cannot be made to Node.js directly, and is specific to tsx
- [X] I understand this form is not for addressing a bug or seeking help

### Feature request

I have a codegen task watching a directory for changes and whenever there is a malformed TS file, TSX will throw a esbuild error and exit the watcher. I wish I could try-catch this error so the watcher restarts the task.

### Motivations

I don't know if it's expected but I think it's a bit unintuitive that I can't trust this:

```ts
try {
   await import('./something')
} catch (e) {
   console.log(e)
}
```

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Not really sure what you're asking/reporting

**Comment by wesbos** [comment]
Also have this issue. I'm dynamically importing a path, and if that file has a syntax error in it, the watcher will crash and I need to restart the whole process. 

In Node, you can catch the error like so:

```js
try {
  const x = await import(`./file-with-syntax-error.js`);
  console.log(x);
} catch (e) {
  console.log(`caught error in try/catch block`);
  console.error(e);
}
```

But with tsx, esbuild throws and error and exits the process:

<img width="832" alt="Screenshot 2024-03-13 at 3 04 16 PM" src="https://github.com/privatenumber/tsx/assets/176013/0d5f4b6d-c211-49e9-b747-9f9c0181c1a4">


I supposed I could run nodemon or something to get around this, but was wondering if I could somehow catch the error on a dynamic require/import.

**Comment by privatenumber** [comment]
Ooh gotcha. The original issue didn't explain that dynamic import errors can't be caught. Thanks for explaining.

This would be a bug, and possibly related to https://github.com/privatenumber/tsx/issues/493

**Comment by wesbos** [comment]
Okay thank you - that is also the issue i have. I think we can close this as a dupe.
