### ISSUE TITLE
node 21 - No inline sourcemap produced

### ISSUE THREAD

**Issue by piec** [privatenumber/tsx#476]
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://stackblitz.com/edit/node-huzszn?file=index.ts

### Version

v4.7.1

### Node.js version

v21.6.1

### Package manager

npm

### Operating system

Linux

### Problem & Expected behavior

Hi,

When using node v21.6.1 it seems that no `//# sourceMappingURL=...` is added at the end of produced files.

Whereas it works with v20.11.0. 
For example using `npx tsx --inspect-brk example.ts` and the source view in chrome://inspect I can see the `//# sourceMappingURL=...` line.

I have just tried a few times to switch between the 2 versions (using `nvm`) and observed this.

In my tsconfig.json, I'm using:
```json
  "compilerOptions": {
    "strict": true,
    "module": "ESNext",
    "target": "ES2020",
    "outDir": "dist",
    "moduleResolution": "Node",
    "lib": ["ESNext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "inlineSourceMap": true,
  },
...
```

Related: https://github.com/privatenumber/tsx/issues/260

Cheers,
Pierre

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by tonisives** [comment]
I have the same problem with node 21 and vscode debugging.

I tested with a simple project. Only with an `index.ts` file with a few lines, and then started it with
`tsx --inspect-brk index.ts`

There is no tsconfig or other files.


I downgraded to brew node@20 and the debugging is now working in vscode.
