### ISSUE TITLE
ColumnTypeUndefinedError with Typeorm, But works with ts-node

### ISSUE THREAD

**Issue by asuradoll** [privatenumber/tsx#485]
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://github.com/asuradoll/MyTypeormEsmMysql

### Version

4.7.1

### Node.js version

18.16.1

### Package manager

yarn

### Operating system

Windows

### Problem & Expected behavior

- What happened?
```
When I run this project, I got an error:
ColumnTypeUndefinedError: Column type for User#firstName is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using 
JavaScript instead of TypeScript you must explicitly provide a column type.
```

- What did you expect instead?
```
Should run normally
```

- Do you have an error stack trace?
```
C:\Users\Administrator\MyTypeormEsmMysql\node_modules\typeorm\decorator\src\decorator\columns\Column.ts:192
                throw new ColumnTypeUndefinedError(object, propertyName)
                      ^


ColumnTypeUndefinedError: Column type for User#firstName is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using 
JavaScript instead of TypeScript you must explicitly provide a column type.
    at <anonymous> (C:\Users\Administrator\MyTypeormEsmMysql\node_modules\typeorm\decorator\src\decorator\columns\Column.ts:192:23)
    at __decorateClass (file:///C:/Users/Administrator/MyTypeormEsmMysql/src/entity/User.ts:1:374)
    at <anonymous> (c:\Users\Administrator\MyTypeormEsmMysql\src\entity\User.ts:10:5)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.1
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
```

- Do you have documentation links?
```
This script works.
   "scripts": {
      "start": "node --loader ts-node/esm src/index.ts",
   }
```

```
I got an error with this script.
   "scripts": {
      "start": "node --loader tsx/esm src/index.ts",
   }
```

- Do you have screenshots?
No

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
The problem is in your error message:
> Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json.

**Comment by asuradoll** [comment]
> The problem is in your error message:
> 
> > Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json.

the option emitDecoratorMetadata already set to true

**Comment by rdev06** [comment]
Hey what happened for this bug?
I am also facing same issue even if `emitDecoratorMetadata` is set to true.

**Comment by privatenumber** [comment]
The limitation with `emitDecoratorMetadata` is documented in the README
