### ISSUE TITLE
The argument 'methodName' must be a method. Received undefined

### ISSUE THREAD

**Issue by darcyrush** [privatenumber/tsx#507]
### Acknowledgements

- [X] I searched existing issues to avoid duplicates
- [X] I understand this is a place to report a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative open source project, and relies on community contributions
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/darcyrush/tsx-methodname-undefined

### Version

4.7.1

### Node.js version

21.2.0

### Package manager

npm

### Operating system

Linux

### Problem & expected behavior (under 200 words)

This is a duplicate of https://github.com/privatenumber/tsx/issues/400 as I can no longer comment in that issue. Having now spent some time with both ESM as well as CJS, I believe the linked issue is still an issue relating to CJS.

In the comments in the linked issue you suggest this is an ESM issue as modules are immutable. However, the project is set up as CJS. I updated the `package.json` to be more explicit about that. I don't use a `tsconfig.json`
```json
"type": "commonjs",
```
I am using tsx in another ESM project with a different mocking approach (using ESMock rather than node's new built-in test module) which works as expected. However, I still expect a CJS project to continue working with mutable mocking libraries using `tsx`.

Please enlighten me if I have misunderstood or misconfigured something.

### Contributions

- [ ] I will open a pull request for this issue
- [ ] I will support the work financially (any amount helps)

**Comment by privatenumber** [comment]
The underlying runtime may be CommonJS, but you're writing in ESM syntax. It would be unexpected if ESM doesn't behave like ESM.

**Comment by darcyrush** [comment]
@privatenumber  Can you expand on what you mean by "writing in ESM syntax"? The only thing I can think you are referring to is the use of `import`s, but this is a widely used TypeScript feature that transpiles down to `require` when the module is set to `commonjs`.

```
tsc --target es2022 --moduleResolution node --module commonjs src/main.ts 
```

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const bootstrap_1 = require("./bootstrap"); // Transpiled to CJS
(0, bootstrap_1.bootstrap)().then();
```

Everything you state in previous comments holds true when the output is esm
```
tsc --target es2022 --moduleResolution node --module esnext src/main.ts 
```
```js
import { bootstrap } from "./bootstrap";
bootstrap().then();
```

I assume TSX transpiles to ESM by default so I added a `tsconfig.json` and used an ENVIRONMENT value before executing `tsx`, but I still get the same issue
```json
{
    "compilerOptions": {
        "target": "ES2022",
        "module": "CommonJS",
        "moduleResolution": "Node"
    }
}
```

```json
"test-tsx": "TSX_TSCONFIG_PATH=./tsconfig.json node --import tsx --test 'test/**/*.test.ts'",
```

**Comment by darcyrush** [comment]
I will try and clarify further. The spec you quote - from my understanding - is for 'newer' ESM modules in JS. But the spec relates only to JS, not TS. We both agree that JS code adhering to ESM using native ES imports, imports those modules as immutable objects.

However, TypeScript has functionality to output to _either_ ESM or CJS, using `module`; 

https://www.typescriptlang.org/docs/handbook/modules/reference.html#emit

> node16 and nodenext describe versions of Node.js that support ES modules, not just projects that use ES modules. Both ESM and CommonJS emit are supported, based on the [detected module format](https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-format-detection) of each file

When `module` is set to `node16` or `nodeNext`, then TypeScript transpiles JS as 'modern' ESM code, using native imports.
When `module` is set to `commonjs` - as is in my case - then TypeScript transpiles JS as 'older' CJS, where `import` is transpiled to `require`.

So regardless if you want to output to ESM or CJS, when writing TypeScript `.ts` files, you can use `import package from 'package'` notation but this doesn't mean the transpiled JS is ESM by default.

It appears that typescript uses the [following logic to determine](https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-format-detection) whether a file is ESM or CJS. If package.json is missing `type`, then `.ts` files are output as CJS by default

> .ts/.tsx/.js/.jsx/.d.ts files are ES modules if the nearest ancestor package.json file contains "type": "module", otherwise CommonJS modules.

**Comment by darcyrush** [comment]
I will update the minimal reproduction repository with a better example, since I believe part of the confusion comes from my (incorrect) test case which indeed only works under ESM...

**Comment by privatenumber** [comment]
Sorry but even if I were to be convinced to accept this issue, it would probably never be a priority for me to work on it unless I'm paid or encountering the issue myself.

I'm not convinced to stray away from spec. But if were you, and I wanted this feature so much to open 3 lengthly issues about it, I'd probably just implement it myself in a fork.
