### ISSUE TITLE
Tsx ignores type commonjs in package.json

### ISSUE THREAD

**Issue by darcyrush** [privatenumber/tsx#508]
### Acknowledgements

- [X] I searched existing issues to avoid duplicates
- [X] I understand this is a place to report a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative open source project, and relies on community contributions
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/darcyrush/tsx-commonjs

### Version

4.7.1

### Node.js version

21.2.0

### Package manager

pnpm

### Operating system

Linux

### Problem & expected behavior (under 200 words)

Opening hopefully the last issue in relation to the previous confusion of https://github.com/privatenumber/tsx/issues/507 and https://github.com/privatenumber/tsx/issues/400. The linked minimal reproduction git repo hopefully show both issues if you uncomment either line in `first.test.ts` and run either npm test script.

There are two possible 'issues' I have discovered;
 - `tsx` seems to ignore `"type": "commonjs"` within `package.json` and transpiles `.ts` files to to ESM JS instead of CJS JS.
 - `tsx` _appears_ to transpile modules to objects using getters for exported functions.

So to explain and clarify my confusion in the previous issues, when `mock.method` is used with tsx, the node mock library fails with 
 > The argument 'methodName' must be a method. Received undefined

This is because `tsx` (or esbuild) appears to transpile `import * as First from "../src/first"` into an object using getters for exported functions. The above error is thrown from the native `node:test` module. This red-herring confused me because `ts-node` transpiles objects as expected - not using getters for the functions. 

Still, this is unexpected since the test code needs to be modified between using `tsx` and `ts-node`, which is not feasible for large projects.

So when using `tsx` and using `mock.getter`, which resolves the first error, I get the following error
 > Cannot redefine property: <property>

Which seems to imply that `tsx` is treating the modules as ESM, which are immutable and cannot be mocked using mutating mocking packages.

### Contributions

- [ ] I will open a pull request for this issue
- [ ] I will support the work financially (any amount helps)

**Comment by privatenumber** [comment]
I've understood you from #400: you want to mock ESM imports, and you're arguing that tsx should follow TypeScript's incorrect implementation of the ESM import spec.

Please refrain from opening multiple issues.
