### ISSUE TITLE
Environment variables support

### ISSUE THREAD

**Issue by marcelldac** [privatenumber/tsx#511]
### Acknowledgements

- [X] I searched existing issues to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and is not for arbitrary Node.js enhancements
- [X] This request cannot be made to Node.js directly, and is specific to tsx
- [X] I understand this form is not for addressing a bug or seeking help
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Feature request

What about environment variables support?

Like the node command:

`node --env-file=.env index.js`

We have something like this in tsx?

### Motivations

Better environment variables hadling

### Contributions

- [ ] I will open a pull request for this issue
- [ ] I will support the work financially (any amount helps)

**Comment by privatenumber** [comment]
Please see the README for how

**Comment by marcelldac** [comment]
Can you help me with this? I did not found.

**Comment by privatenumber** [comment]
I updated the README to explain this better instead as this Issue is an indication of poor documentation. Hopefully that helps.

**Comment by marcelldac** [comment]
tks

**Comment by x-tropy** [comment]
```
tsx --env-file=.env drizzle/seed.ts
```
What I got is:
```
/usr/local/bin/node: bad option: --env-file=.env
```

not sure why
