### ISSUE TITLE
Typescript REPL

### ISSUE THREAD

**Issue by 500-internal-server-error** [privatenumber/tsx#515]
### Acknowledgements

- [X] I searched existing issues to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and is not for arbitrary Node.js enhancements
- [X] This request cannot be made to Node.js directly, and is specific to tsx
- [X] I understand this form is not for addressing a bug or seeking help
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Feature request

A way to interactively run Typescript lines, similar to how Node runs Javascript lines.

### Motivations

A Typescript REPL to run code directly would be more convenient than having to write a file before being able to run it.

### Alternatives

Writing to a file before running it is one way, but at that point I might as well compile and run it myself.

### Additional context

Coming from `ts-node`, which seems to be [horribly broken](https://github.com/TypeStrong/ts-node/issues?q=is%3Aissue+is%3Aopen+err_unknown_file_extension) and incompatible with `"type": "module"` in `package.json` and modern Node versions (versions past 18.19.x). `ts-node src/index.ts` allowed me to run source files as expected, but `ts-node` also allowed me to play around with Typescript in a REPL similar to how `node` allows me to play around with Javascript in a REPL. I could even import my own code in this REPL. It was nice for little experiments, poking around and seeing how well a particular piece of my codebase works without having to run the entire project - for example, I could play around and see how my `class Database` in `src/database.ts` or my `function generateRandomInt(minInclusive: number, maxInclusive: number): number` in `src/utils.ts` works without having to run through everything in `src/index.ts`.

Going into `tsx`, I (maybe wrongly) expected a similar experience, where `tsx src/index.ts` would run my Typescript source files, and `tsx` would give me a way to interact with pieces of my codebase. I was quite surprised when `tsx` just ran `node` :)

### Contributions

- [ ] I will open a pull request for this issue
- [ ] I will support the work financially (any amount helps)

**Comment by privatenumber** [comment]
This is already possible. Please read the README. If it's not working expectedly, please file a bug report.
