### ISSUE TITLE
Feature request: Extend 'tsx watch' for run command on detects file changes

### ISSUE THREAD

**Issue by jellydn** [privatenumber/tsx#521]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and is not for arbitrary Node.js enhancements
- [X] This request cannot be made to Node.js directly, and is specific to tsx
- [X] I understand this form is not for addressing a bug or seeking help
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Feature request

I'd like to propose an enhancement to `tsx watch` for triggering other npm scripts or any command.

### Motivations

I have 2 commands, one for running API and the other for generating swagger/openapi.

```json
"dev": "run-p -l dev:*",
"dev:api": "npx tsx watch ./server.ts | npx pino-pretty",
"dev:swagger": "wait-on -c ./wait-on.config.json -l && npm run generate:swagger",
```

Is that possible to re-run `dev:swagger` command when `tsx watch` detects file changes? 

```sh
"dev:watch": "tsx watch ./server.ts --on-change='run run generate:swagger'",
```

### Contributions

- [ ] I'm interested in working on this issue
- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Your script gets re-run on watch, so you can simply run `generate:swagger` from your script via [`spawnSync`](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options).
