### ISSUE TITLE
tsx can't run code with endent

### ISSUE THREAD

**Issue by nicroto** [privatenumber/tsx#533]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a place to report a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative open source project, and relies on community contributions
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://gist.github.com/nicroto/a2c73922a5e8f83d7673212104fd22a6

### Version

v4.7.2

### Node.js version

v21.7.1

### Package manager

npm

### Operating system

macOS

### Problem & expected behavior (under 200 words)

**What happened**

- I get an Error: `TypeError: endent is not a function`

**What I expected**

- Not to produce error

**Error stack trace**

```
TypeError: endent is not a function
    at main (test.ts:9:15)
    at <anonymous> (test.ts:12:1)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)
```

### Contributions

- [ ] I'm interested in working on this issue
- [ ] I'm willing to offer financial support

**Comment by nicroto** [comment]
I've also posted a question in SO: https://stackoverflow.com/questions/78357468/is-there-a-way-to-run-tsx-with-endent-and-similar-tagged-template-literals

**Comment by nicroto** [comment]
@privatenumber does the example I gave not reproduce the issue on your end?

**Comment by privatenumber** [comment]
I haven't tried. Please use the reproduction guidelines in the issue template.
