### ISSUE TITLE
Is Bundle / Compile command planned?

### ISSUE THREAD

**Issue by endel** [privatenumber/tsx#540]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand tsx aims for TypeScript parity and is not for arbitrary Node.js enhancements
- [X] This request cannot be made to Node.js directly, and is specific to tsx
- [X] I understand this form is not for addressing a bug or seeking help
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Feature request

Allow bundling a Node.js app into JavaScript, so it can be executed later by `node` directly:

```
tsx bundle index.ts
```

Maybe some runtime configs could be lost on the final bundled file, but it may serve well in most use cases.

### Motivations

Execute the final built `.js` file via `node`.

As `tsx` is capable of combining TypeScript configs and use `esbuild` under the hood, would it be viable to use `tsconfig.json` configuration (such as `outDir`) to generate a bundled `.js` output?

### Alternatives

```
npx esbuild src/index.ts --bundle --platform=node --packages=external  > my-built-file.js
```

### Contributions

- [ ] I'm interested in working on this issue
- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Thanks for the request!

Bundling is out of scope for tsx, but I have pkgroll for that which is more tailored for bundling: https://github.com/privatenumber/pkgroll

This is how tsx uses it (how to bundle is inferred from `package.json`):
https://github.com/privatenumber/tsx/blob/4f515ab0bb8f3c8c610dc57556b978cbf90a5560/package.json#L51
