### ISSUE TITLE
Regression with MikroORM introduced with tsx v4.9.1 

### ISSUE THREAD

**Issue by DASPRiD** [privatenumber/tsx#541]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a place to report a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative open source project, and relies on community contributions
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/node-wp3mk9

### Version

v4.9.1

### Node.js version

v20.12.2

### Package manager

pnpm

### Operating system

Linux

### Problem & expected behavior (under 200 words)

TSX v4.9.1 introduced a regression when trying to load .ts config files for MikroORM. This was working fine so far, including v.4.9.0. I only see a single commit for v4.9.1, so that one must have introduced the regression:

https://github.com/privatenumber/tsx/commit/96bc59680c7300ab6f4f740da26fa16e1970c7c0

### Contributions

- [ ] I'm interested in working on this issue
- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Thanks for the report!

I guess we didn't have a test to cover this use case. Would you mind opening a PR with a test (& fix if youre able to)?

**Comment by privatenumber** [comment]
Based on the reproduction, looks like this was addressed via #544
