### ISSUE TITLE
Modules imported dynamically from an absolute path are not loaded/handled by tsx v4.9.1

### ISSUE THREAD

**Issue by fardjad** [privatenumber/tsx#543]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a place to report a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative open source project, and relies on community contributions
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/tsx-4-9-1-import-from-absolute-path-issue

### Version

4.9.1

### Node.js version

v20.12.2

### Package manager

npm

### Operating system

macOS

### Problem & expected behavior (under 200 words)

- What happened

The newly released version v4.9.1 doesn't handle absolute paths (4.9.0 doesn't have this issue).

- What I expected

I expected to be able to run the following with `tsx index.mts`:

```typescript
// index.mts

import path from "node:path";
import { fileURLToPath } from "node:url";
import fs from "node:fs";

const __dirname = path.dirname(fileURLToPath(new URL(import.meta.url)));
const moduleRelativePath = "./hello.mts";
const moduleAbsolutePath = path.resolve(__dirname, moduleRelativePath);

fs.writeFileSync(moduleAbsolutePath, `export const message = "Hello, world!";`);

await import(moduleAbsolutePath); // Doesn't work
```

- Error stack trace

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".mts" for <redacted>/hello.mts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:866:22)
    at async x (file:///<redacted>/.npm/_npx/dcefadc2074ecd1f/node_modules/tsx/dist/esm/index.mjs?1714902597374:2:1744)
    at async nextLoad (node:internal/modules/esm/hooks:866:22)
    at async Hooks.load (node:internal/modules/esm/hooks:449:20)
    at async handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

- Documentation links

It happens because an absolute path is not considered a path in the custom resolver and then the early return at the end of the if block skips the resolution:

https://github.com/privatenumber/tsx/blob/96bc59680c7300ab6f4f740da26fa16e1970c7c0/src/esm/hook/resolve.ts#L130-L150

- Screenshots

![image](https://github.com/privatenumber/tsx/assets/817642/6be3a907-03ab-4a6d-97d2-0e9ee454877d)

### Contributions

- [X] I'm interested in working on this issue
- [ ] I'm willing to offer financial support

**Comment by hatemjaber** [comment]
I just ran into the same issue and confirm... I reverted to 4.7.1 for now and project is back working.

**Comment by hatemjaber** [comment]
I was just confirming that it's an issues after losing hours of my time
