### ISSUE TITLE
[ESM / Node v22] Broken import of a correctly bundled library 

### ISSUE THREAD

**Issue by damianobarbati** [privatenumber/tsx#553]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a place to report a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative open source project, and relies on community contributions
- [X] I have read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/node-cfvrct?file=index.ts

Or:
```ts
// index.ts
import MapsSearch, { isUnexpected } from '@azure-rest/maps-search';
console.log(MapsSearch, isUnexpected);
```

Result (add to package.json scripts `"start": "tsx index.ts"`):
```sh
pnpm start
{
  default: [Function: MapsSearch],
  isUnexpected: [Function: isUnexpected]
} [Function: isUnexpected]
```

### Version

v4.10.2

### Node.js version

v22.1

### Package manager

pnpm

### Operating system

macOS

### Problem & expected behavior (under 200 words)

Running the code in the sandbox under node v22.1 result in a weird resolution alà CJS:
```js
import MapsSearch, { isUnexpected } from '@azure-rest/maps-search';
console.log(MapSearch);
```
Output:
```sh
{
  default: [Function: MapsSearch],
  isUnexpected: [Function: isUnexpected]
}
```

Running the same code with vitest (not using tsx) looks ok, and the import is respecting the default in the MapsSearch variable.

Keep in mind the codesandbox is giving yet another error, but on Stackblitz is not possible to change the node version to the last one.

### Contributions

- [ ] I'm interested in working on this issue
- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Your reproduction seems to show a different error than what you're reporting.

Is there a reason why you're using an outdated version of tsx? And are all the files and deps necessary? For example `@types/node` can definitely be removed.

**Comment by damianobarbati** [comment]
@privatenumber sorry for this, I created a proper repro on github as StackBlitz can't enforce node version. 
You should be able to reproduce copy-pasting the commands assuming you have nvm. Let me know if I can help further.

**Comment by privatenumber** [comment]
Duplicate of https://github.com/privatenumber/tsx/issues/38
