### ISSUE TITLE
Parsing error when using variable `of`

### ISSUE THREAD

**Issue by errorx666** [privatenumber/tsx#556]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/stackblitz-starters-gtalwu?file=tsconfig.json

### Problem & expected behavior (under 200 words)

npm start

Expected: code runs
Actual: Parse error

Works with bun

### Bugs are expected to be fixed by those affected by it

- [x] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by errorx666** [comment]
I started with a real-world error and stripped out as much as possible while still preserving the error.

**Comment by privatenumber** [comment]
I appreciate the effort but the reproduction is not minimal at all... There's 7 files and 11 dependencies. Please minimize it so `tsx` is the only dependency.

**Comment by errorx666** [comment]
@privatenumber I have reduced it to one file and one external dependency.  Please check again..

**Comment by privatenumber** [comment]
Thanks, I appreciate it!

I believe the root problem is in `es-module-lexer` assuming `of` is a reserved identifier. I reported it here: https://github.com/guybedford/es-module-lexer/issues/173

I also noticed an opportunity to skip the parsing completely in your case as the parsing is only used to detect dynamic imports, which you're not using. Upgrading to tsx [v4.10.3](https://github.com/privatenumber/tsx/releases/tag/v4.10.3) should fix your use-case.

**Comment by errorx666** [comment]
Thank you for the quick turnaround!  I would never have thought of that.

**Comment by privatenumber** [comment]
Fixed in https://github.com/guybedford/es-module-lexer/issues/173

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.10.5

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
