### ISSUE TITLE
Cannot be used with Nuxt

### ISSUE THREAD

**Issue by userquin** [privatenumber/tsx#557]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/unocss/unocss/tree/feat/unconfig

### Problem & expected behavior (under 200 words)

Nuxt requires running `nuxt/nuxi prepare` command to generate `.nuxt` folder with a lot of stuff, included the `tsconfig.json` file, the root `tsconfig.json` file contains a reference to the generated one:
```json
{
  "extends": "./.nuxt/tsconfig.json"
}
```

I guess it is a side effect here https://github.com/privatenumber/tsx/blob/master/src/esm/hook/load.ts#L10-L15 , since it is parsing the `tsconfig.json` file. Maybe the import can be deferred until calling `load` using dynamic import instead static one.

I'll try to create a minimal reproduction, we've changed `importx`  and `unconfig` repos to allow use `tsx`.

To reproduce the error in the UnoCSS PR branch, install dependencies `pnpm install --frozen-lockfile` then change to `interactive` folder and run `pnpm nuxi prepare`.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Thanks for the issue.

Sorry, I don't have the context of Nuxt and Nuxi. I'm having trouble figuring out if you're actually reporting a tsx bug, or opening a feature request for better support for Nuxt.

As per the warning in the issue template, there doesn't seem to be a minimal reproduction so I'm going to close this for now.

Would you mind updating the issue so it's less about Nuxt and more about the actual tsx bug + minimal reproduction? Let me know when it's updated and I'll re-open.

**Comment by userquin** [comment]
Sure, I'm trying to figure out what's the problem, we  have a few dependencies: unconfig, importx and jiti/tsx

**Comment by privatenumber** [comment]
Anthony filled me in. https://github.com/privatenumber/tsx/releases/tag/v4.11.0 should silence errors if the auto-detected tsconfig is invalid (only explicitly passed in ones error).

**Comment by userquin** [comment]
@privatenumber thx, it should be fixed also in `importx` on next release, tested on my local and works, thx again ❤️ :

![imagen](https://github.com/privatenumber/tsx/assets/6311119/5df89c1e-52bf-423f-b610-88225a5b32b3)
