### ISSUE TITLE
ERR_UNKNOWN_FILE_EXTENSION with `import 'tsx'`, but `--import tsx` works

### ISSUE THREAD

**Issue by SystemParadox** [privatenumber/tsx#572]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/node-57nwqh?file=index.mjs

### Problem & expected behavior (under 200 words)

- `node index.mjs` with `import 'tsx'` results in `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`
    - According to [the docs](https://tsx.is/node/#programmatic-api) this should work.
- `node --import tsx index.mjs` works

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Your minimal repro doesn't use tsx.

**Comment by SystemParadox** [comment]
Oops sorry, looks like that got removed while I was testing. I have put the `import 'tsx'` back in but the result is exactly the same.

**Comment by privatenumber** [comment]
Addressed via https://github.com/privatenumber/tsx/commit/9f04dae4167bfeadf7f69920958bb19f86572a08

**Comment by SystemParadox** [comment]
Ok thanks. I did wonder if this might be the answer but I'm not entirely clear on the reason for it. My understanding was that all of `import 'tsx'` should execute first (which would include the `register` call) before we try to `import './foo.ts'`.

Possibly something to do with parallelisation? Or is it just that node doesn't want to complicate things by allowing hooks to be added within the loading of a file?
