### ISSUE TITLE
Module cannot be resolved with `tsx@4.13.1`

### ISSUE THREAD

**Issue by karlhorky** [privatenumber/tsx#578]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://codesandbox.io/p/devbox/tsx-4-13-1-module-resolution-bug-kj3c2v?file=%2Findex.ts%3A3%2C20

### Problem & expected behavior (under 200 words)

Originally reported in [this comment](https://github.com/privatenumber/tsx/issues/575#issuecomment-2154295107) (marked off-topic)

- What happened

`tsx@4.13.1` cannot resolve the `cache` import from `next/dist/compiled/react/index.js`

- What I expected

For the `cache` import from `next/dist/compiled/react/index.js` to be resolved, like in `tsx@4.13.0`

- Error stack trace

```
> tsx index.ts

/project/workspace/index.ts:1
import { cache } from "next/dist/compiled/react/index.js";
         ^

SyntaxError: The requested module 'next/dist/compiled/react/index.js' does not provide an export named 'cache'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.0
 ELIFECYCLE  Command failed with exit code 1
```

- Documentation links
- Screenshots

[`tsx@4.13.1` (failing)](https://codesandbox.io/p/devbox/tsx-4-13-1-module-resolution-bug-kj3c2v?file=%2Findex.ts%3A3%2C20)

![Screenshot 2024-06-07 at 11 28 23](https://github.com/privatenumber/tsx/assets/1935696/8a989c3f-9e40-41f7-a1c2-453704fcdaee)

[`tsx@4.13.0` (working)](https://codesandbox.io/p/devbox/tsx-4-13-0-module-resolution-bug-not-present-nqg9fs?file=%2Findex.ts)

![Screenshot 2024-06-07 at 11 32 24](https://github.com/privatenumber/tsx/assets/1935696/0c1d9775-9318-48a1-aee3-b62abe104451)

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by karlhorky** [comment]
@privatenumber sorry, the default of CodeSandbox changed to private Devboxes a while ago

Fixed now - both Devboxes are now public.

**Comment by wodka** [comment]
I am having this exact error starting with 4.15 :/ happening with groq-sdk. downgrading to 4.14.1 works

```ts
import { ReadableStream, type Response } from "../_shims/index";
         ^

SyntaxError: The requested module 'groq-sdk/_shims/index' does not provide an export named 'ReadableStream'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```
