### ISSUE TITLE
[Regression] ESM module import using the # import pattern no longer works since 4.12.0

### ISSUE THREAD

**Issue by FredTreg** [privatenumber/tsx#579]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/node-c5jsr8

### Problem & expected behavior (under 200 words)

The stackblitz will work if moving back to tsx 4.11.2

Basically using
```
"imports": {
    "#*": {
      "production": "./dist/*",
      "default": "./src/*"
    }
  },
```
in package.json no longer works in 4.12.0

I assume commit https://github.com/privatenumber/tsx/commit/72d08965f9f1dd348b6017520ad63bc8373edc72 is responsible for the issue as a path starting with '#' may not be considered a unix path?

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.13.3

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
