### ISSUE TITLE
Since v4.12 ,code execution on the windows has been consistently reporting errors

### ISSUE THREAD

**Issue by wanpan11** [privatenumber/tsx#580]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/ant-design/ant-design

### Problem & expected behavior (under 200 words)

Subsequent versions starting from v4.12 cannot execute properly on Windows

**bad**

![d6805f739e899815ac1a8c0490783966](https://github.com/privatenumber/tsx/assets/38714194/a3b25b41-3d47-43d7-83f8-9970d899772d)

![dc89d7036c3e2302cc3e25be62bc0d3d](https://github.com/privatenumber/tsx/assets/38714194/6146942c-0309-4e78-ba0d-21790e5717d0)

**good**

![8e02c708bc2d11d9be10d1c9986c37eb](https://github.com/privatenumber/tsx/assets/38714194/267e83ca-5709-4e44-b93a-d0f3a7e0c406)

But if you really need to explain, keep it under 200 words:

The Ant Design repository keeps failing to build during startup, with a prompt of missing modules. There are issues with both v4.12 and v4.13

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by wanpan11** [comment]
Can you tell me why this issue has been closed? Thank you 💕

**Comment by privatenumber** [comment]
You ignored the issue form instructions
