### ISSUE TITLE
[Regression] ERROR: Transforming JavaScript decorators to the configured target environment ("node21.3.0") is not supported yet

### ISSUE THREAD

**Issue by TomChv** [privatenumber/tsx#582]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/TomChv/tsx-repro-regression-decorator-error

### Problem & expected behavior (under 200 words)

`v4.13.1` (and all versions above `v4.13.0`) broke the decorators transpilation.

```shell
Transforming JavaScript decorators to the configured target environment ("node21.3.0") is not supported yet
```

I tested with node `v21.3.0` and `v22.2.0`.

Everything went great before that so I assume it's a regression.
You'll find all the details in my reproduction repository.

I also read the issue https://github.com/privatenumber/tsx/issues/393 but I think my problem is different because everything was fine before the version ugprade. And I'm not able to comment on it because it's locked.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.13.3

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
