### ISSUE TITLE
CommonJS directory import fails

### ISSUE THREAD

**Issue by marvson** [privatenumber/tsx#583]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/marvson/tsx-reproduction

### Problem & expected behavior (under 200 words)

But if you really need to explain, keep it under 200 words:
- What happened
   After updating to 4.13.0, the reproduction fails, it works fine on 4.12.1.

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.13.3

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
