### ISSUE TITLE
`ChildProcess.kill('SIGINT')` not working

### ISSUE THREAD

**Issue by MinecraftPEayer** [privatenumber/tsx#591]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/node-cvmclj?file=index.ts,child.ts

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Your problem here is with npx not relaying the SIGINT. If you call tsx directly, it works fine.
