### ISSUE TITLE
Reproduction with node-postgres of "Cannot import named export from a typescript file in a workspace package if entry is using es modules and other package is not."

### ISSUE THREAD

**Issue by saltman424** [privatenumber/tsx#593]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/stackblitz-starters-g6pt9g?file=index.mts

### Problem & expected behavior (under 200 words)

Reproduced https://github.com/privatenumber/tsx/issues/38 with [node-postgres](https://github.com/brianc/node-postgres)

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Thanks for providing the repro—it helps a lot with understanding what you did.

I've never used `node-postgres` before so I assumed the package was [`node-postgres`](https://unpkg.com/node-postgres@0.6.2/index.js).

The [`pg` package](https://unpkg.com/pg@8.12.0/lib/index.js) doesn't do named exports in a statically analyzable way, so it's hitting the same limitation in Node as with `lodash` (this isn't a tsx issue or limitation).

You can either file an issue with pg to make imports statically analyzable or with Node to improve their static analysis.
