### ISSUE TITLE
Cannot imports CSJ from ESM package (`type=module`)

### ISSUE THREAD

**Issue by hugo082** [privatenumber/tsx#594]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://codesandbox.io/p/devbox/small-field-2xdyc7

### Problem & expected behavior (under 200 words)

When the package is configured to `type=module`, tsx fails to load CJS modules.

```
import { uniq } from "lodash";
         ^

SyntaxError: The requested module 'lodash' does not provide an export named 'uniq'
  ...

Node.js v20.12.1
```

Note that if the package type is not `module`, it works.

I found https://github.com/privatenumber/tsx/issues/38 which may be related but you mentioned that the issue has been resolved in v4.12.0.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Read the last comment in #38.
