### ISSUE TITLE
Cannot resolve `.` path

### ISSUE THREAD

**Issue by sxzz** [privatenumber/tsx#599]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/sxzz/tsx-issue

### Problem & expected behavior (under 200 words)

```ts
import test from '.' // ❌ not working
// import test from './index' // ✅ working
```

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Your reproduction doesn't reproduce the bug for me:
```sh
pnpm tsx demo.ts
```

**Comment by privatenumber** [comment]
I've added a test case to confirm this is working: https://github.com/privatenumber/tsx/commit/c67e3baefdb4b38d44779a44e21f2a989482911c

**Comment by sxzz** [comment]
Using CLI works, but using Node API does not. Run `node index.js` instead.  

(Sorry for forgetting to mention how to run it)

**Comment by privatenumber** [comment]
Gotcha, no worries.

This was fixed inadvertently via https://github.com/privatenumber/tsx/releases/tag/v4.15.8
