### ISSUE TITLE
Very bad name

### ISSUE THREAD

**Issue by iccicci** [privatenumber/tsx#601]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://www.google.com/search?q=issue+tsx+typescript

### Problem & expected behavior (under 200 words)

Great package! Simply awesome!

I'm not reporting a technical bug, but a huge product design bug: `tsx` is globally recognized as the react.js file name extension, not this exceptional product; it's really hard to search relevant articles.

I strongly suggest to rename it with a longer not ambiguous name.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by iccicci** [comment]
I'm astonished!

**Comment by privatenumber** [comment]
Closing as this is a bug tracker.

Feel free to post this in the Discussions in the developments repo (sponsors only).
