### ISSUE TITLE
Imports with `.` and no explicit file extension no longer work

### ISSUE THREAD

**Issue by Jiralite** [privatenumber/tsx#604]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/Jiralite/tsx-4.15.8-1

### Problem & expected behavior (under 200 words)

Imports with a `.` in them fail to resolve without an extension. This worked fine in 4.15.7 and before, but not with https://github.com/privatenumber/tsx/releases/tag/v4.15.8 which was recently released.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by fernandocanizo** [comment]
I can confirm this is happening here to. We are using in our `package.json` the script:
```
"scripts": {
   "dev": "pnpx tsx ./server.js",
   ...

}
```

Which automatically uses the latest `tsx`, our code works perfectly with v4.15.7 but now, without having touched anything, it stopped working.

I understand that the way we were using `tsx` would have blown on our faces anyway, but maybe some other people is getting caught by this and they don't automatically update their `tsx` dependency.

So at least you should have bumped a major version, as this is a **breaking change**.

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.15.9

If you rely on this project, please consider [making a donation](https://github.com/sponsors/privatenumber) :heart: :pray:

**Comment by privatenumber** [comment]
As per the [Contributing Guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md), I've hid comments that don't contribute towards fixing the bug.
