### ISSUE TITLE
Hot-reloading not working with Docker

### ISSUE THREAD

**Issue by joaocasarin** [privatenumber/tsx#610]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/joaocasarin/tsx-hotreload-docker-bug

### Problem & expected behavior (under 200 words)

- What happened: after modifying my code, `tsx watch index.ts` did not auto-reload the app
- What I expected: `tsx watch index.ts` should auto reload the application, even if it is running inside a container, because the source code is added as a volume to it, so all changes are reflected to the file inside the container, triggering the reload.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by joaocasarin** [comment]
@privatenumber if this is a duplicate, could you point me to the first opened issue about it? I could not find it...

**Comment by GeekCornerGH** [comment]
The issue you're looking for is #266
Workaround is included in that issue too
