### ISSUE TITLE
`ERR_PACKAGE_IMPORT_NOT_DEFINED` on 4.16.0

### ISSUE THREAD

**Issue by d-roak** [privatenumber/tsx#612]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/topology-foundation/ts-topology/tree/ae148aa031edcc0c139db8eca22abf4d95d593aa

### Problem & expected behavior (under 200 words)

Upgrading to 4.16.0 (from 4.15.7) breaks with the following message:

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/f6b79e7e-e551-4f0d-9dc8-ce16b2394b82">

I lack the understanding of ESM to debug it further.

The other dependency that is involved with the breaking is [uint8arrays](https://github.com/achingbrain/uint8arrays)

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [X] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
The reproduction must be minimal
