### ISSUE TITLE
Not supported to run in the VSCode extension

### ISSUE THREAD

**Issue by sxzz** [privatenumber/tsx#624]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/sxzz/tsx-vscode-ext

### Problem & expected behavior (under 200 words)

Run `pnpm lint`; it works. However, in the VSCode environment, the ESLint extension shows an error.

```
[Error - 10:20:51 AM] Request textDocument/diagnostic failed.
  Message: Request textDocument/diagnostic failed with message: Cannot read properties of undefined (reading 'size')
  Code: -32603 
```

The full error stack:

```ts
TypeError [Error] [TransformError]: Cannot read properties of undefined (reading 'size')
    at normalizeSpawnArguments (node:child_process:726:34)
    at Object.spawn (node:child_process:792:13)
    at ensureServiceIsRunning (/path/tsx-vscode-ext/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1975:29)
    at transform (/path/tsx-vscode-ext/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1875:37)
    at file:///path/tsx-vscode-ext/node_modules/.pnpm/tsx@4.16.2/node_modules/tsx/dist/index-DeKCL_WS.mjs:16:2654
    at applyTransformers (file:///path/tsx-vscode-ext/node_modules/.pnpm/tsx@4.16.2/node_modules/tsx/dist/index-DeKCL_WS.mjs:16:1266)
    at transform (file:///path/tsx-vscode-ext/node_modules/.pnpm/tsx@4.16.2/node_modules/tsx/dist/index-DeKCL_WS.mjs:16:2601)
    at load (file:///path/tsx-vscode-ext/node_modules/.pnpm/tsx@4.16.2/node_modules/tsx/dist/esm/index.mjs?1722219946759:2:2245)
    at async nextLoad (node:internal/modules/esm/hooks:833:22)
    at async Hooks.load (node:internal/modules/esm/hooks:416:20)
```

### version
VSCode: `1.91.1`
Node: `20.9.0`

---

My repo, https://github.com/sxzz/eslint-config, uses https://github.com/antfu/eslint-ts-patch powered by tsx and encounters the same error in VSCode.

I can also confirm that this issue also occurs in Vue Language Tools.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
I haven't been able to reproduce this.

I cloned your repo, ran `nvm i 20.9.0; pnpm lint` and it works fine.

I've never used the VSCode ESLint extension but I tried installing it and I'm not even sure how to get it to run or see if it's working/erroring.

I checked out `eslint-ts-patch` and saw this. Is this relevant?
https://github.com/antfu/eslint-ts-patch#integrations

**Comment by sxzz** [comment]
Forgot to mention 😂
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/a02eb65c-368f-4d5e-83e7-f28dfa299971">

`eslint-ts-patch` refers to VSCode 1.89, but in the latest version 1.91.1, Node has been updated. Therefore, it's not due to an outdated Node version. The same version works fine in CLI.

**Comment by privatenumber** [comment]
Thanks, I was able to reproduce it!

Debugging it, it actually doesn't seem to be a tsx issue. As you can see from the error stack, it's coming from esbuild when it tries to spawn:

```sh
TypeError: Cannot read properties of undefined (reading 'size')
    at normalizeSpawnArguments (node:child_process:726:34)
    at Object.spawn (node:child_process:792:13)
    at ensureServiceIsRunning (/github/privatenumber/tsx/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1993:29)
```

In esbuild, this is the line:
https://github.com/evanw/esbuild/blob/78f89e41d5e8a7088f4820351c6305cc339f8820/lib/npm/node.ts#L257

It looks like a pretty simple `spawn` though, so I went into the Node.js v20.9.0 source but I couldn't trace it back:
- https://github.com/nodejs/node/blob/v20.9.0/lib/child_process.js#L726 is not in `normalizeSpawnArguments`
- https://github.com/nodejs/node/blob/v20.9.0/lib/child_process.js#L792 is a blank line

If VSCode bundles its own version of Node with it, I wonder if it's a modified fork?

**Comment by sxzz** [comment]
I tried running it on VSCodium (a community fork of VSCode). It works well, so I suspect the issue might be with VSCode.

However, if I use `esbuild` alone, it works on both VSCode, VSCode Insiders, and VSCodium. I guess it might have been broken by some features used by `tsx`?

**Comment by sxzz** [comment]
Can confirm that the bug is caused by VSCode. I guess related to `module.register` API.

**Comment by sxzz** [comment]
Raise an issue upstream: https://github.com/microsoft/vscode/issues/224426

**Comment by privatenumber** [comment]
Wow very nice work @sxzz 🔥 Will wait for it to be resolved upstream.

How did you manage to see into `normalizeSpawnArguments`?

**Comment by sxzz** [comment]
- Try debugging a VSCode extension (such as https://github.com/vuejs/language-tools), clone it and press F5.
- Set a breakpoint in any code, and through the VSCode debug console, get the `process.debugPort` port number.
- Open `chrome://inspect/` in Chrome, click on `Open dedicated DevTools for Node`.
- In the new window's connection tab, add `localhost:[process.debugPort]`.
- You can then see the internal code of node in the sources tab.

<img width="928" alt="image" src="https://github.com/user-attachments/assets/15b80bc6-db4e-40aa-b522-856f3b44e2b4">

**Comment by privatenumber** [comment]
Ah amazing! Thanks for the tip @sxzz

**Comment by sxzz** [comment]
Fixed in the latest VSCode Insiders. Follow https://github.com/microsoft/vscode/issues/224426 for release updates.
