### ISSUE TITLE
regression: path ".." no longer supported

### ISSUE THREAD

**Issue by maxpatiiuk** [privatenumber/tsx#626]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/node-kvpuzc?file=README.md

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by maxpatiiuk** [comment]
Also, we used to do `import("./bug.ts")` before but that no longer works as TSX tries to import `bug.ts.ts`

**Comment by privatenumber** [comment]
This issue is now resolved in [v4.16.4](https://github.com/privatenumber/tsx/releases/tag/v4.16.4).

If you're able to, [your sponsorship](https://github.com/sponsors/privatenumber) would be very much appreciated.

**Comment by privatenumber** [comment]
> Also, we used to do `import("./bug.ts")` before but that no longer works as TSX tries to import `bug.ts.ts`

Works fine in your repro:

https://stackblitz.com/edit/node-wmebgm?file=dir%2Fentry.ts
