### ISSUE TITLE
ESM only: The requested module './generated/index.js' does not provide an export named 'ConfigurationSetting'

### ISSUE THREAD

**Issue by jeremymeng** [privatenumber/tsx#630]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/jeremymeng/tsx-repo

### Problem & expected behavior (under 200 words)

Skip this section and let your reproduction do the talking...

Not sure whether it is related, but we are using `export * from "./models/index.js"; ` pattern in ./generated/index.js

But if you really need to explain, keep it under 200 words:
- What happened
- What I expected
- Error stack trace
- Documentation links
- Screenshots

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
This is not a bug. The error happens because the TS compiler cant tell if you're importing a type or a run-time value.

To be explicit, you can use `import type`.

For the TS compiler to warn you about this, you can enable https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax
