### ISSUE TITLE
how to run with pm2?

### ISSUE THREAD

**Issue by veeramarni** [privatenumber/tsx#631]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/veeramarni/fullstack-pro

### Problem & expected behavior (under 200 words)

I don't find any notes on running with `pm2` If you have any documents please share them.

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [X] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Sorry this is a bug tracker. If you need support, you can sponsor the project to join the forum and ask your question there.
