### ISSUE TITLE
Unexpected identifier assert 

### ISSUE THREAD

**Issue by vuthanhtrung2010** [privatenumber/tsx#632]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/user-attachments/assets/981fe72b-adad-4ad4-b3ae-90bd0b464180

### Problem & expected behavior (under 200 words)

Hi this is my tsconfig.json
```json
{
  "compilerOptions": {
    /* Language and Environment */
    "target": "ES2022" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,

    /* Modules */
    "module": "ES2022" /* Specify what module code is generated. */,
    "lib": ["ES2022"],
    "moduleResolution": "Node",
    "allowImportingTsExtensions": true,
    "allowJs": true,
    "rootDir": "src/",
    "baseUrl": "src/",
    "importHelpers": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "types": ["node", "discord.js", "discord-hybrid-sharding"],
    "allowSyntheticDefaultImports": true,

    /* Type Checking */
    "strict": true /* Enable all strict type-checking options. */,
    "noImplicitAny": true,
    "skipLibCheck": true /* Skip type checking all .d.ts files. */,

    /* Prevent Output */
    "noEmit": true /* Do not emit outputs. */
  },
  "exclude": ["eslint.config.mjs"]
}
```
![image-42](https://github.com/user-attachments/assets/981fe72b-adad-4ad4-b3ae-90bd0b464180)

Note the error started from my friend lib. Have assert type JSON. Well I tried to modify node_modules and it works well. that's esm import. So unexpected identifier assert in esm import? That's false. I set to type: module already in package.json

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Please read the issue template warning about reproductions
