### ISSUE TITLE
`watch --include=.dotfile` does not watch the .dotfile

### ISSUE THREAD

**Issue by iki** [privatenumber/tsx#642]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://gist.github.com/iki/51b13522da866059ee4d7b1065d5165c

### Problem & expected behavior (under 200 words)

1. Run tsx watch
  ```sh
  tsx watch --clear-screen=false --include .env -r dotenv-flow/config -- index.ts
  ```

2. Change content of `.env`
  - Expected result: tsx restarts the script
  - Actual result: dotfiles are [ignored](https://github.com/privatenumber/tsx/blob/master/src/watch/index.ts#L211) (both patterns have impact)

Proposed solution:
  - What is the use case for ignoring dot files? Can it be removed from defaults? Or opted-out?
  - Surprisingly the dot directories glob `**/.*/**` has impact too (I tried to remove them). Can this be fixed to match dot directories only?

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Duplicate of https://github.com/privatenumber/tsx/issues/210

I'm actually working on this now though so expect it soon!
