### ISSUE TITLE
`tsx` not working with the new `${configDir}` template variable from `tsconfig.json`

### ISSUE THREAD

**Issue by ivodolenc** [privatenumber/tsx#649]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

-

### Problem & expected behavior (under 200 words)

Hi, `TypeScript` released a new [`${configDir}`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html#the-configdir-template-variable-for-configuration-files) template variable option in `5.5.0` version.

This is super useful when using `shared` configs from `npm`.

I just tested it and `tsx` doesn't seem to resolve the path alias as it should and throws error when building.

Here's a simple example of `tsconfig` that doesn't work when `tsx` starts building, but the alias works normally in the project as expected, with no errors:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "baseUrl": "${configDir}",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["src/**/*"]
}
```

Here is a simple example of `tsconfig` working normally when `tsx` starts building and alias also working normally without errors:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["src/**/*"]
}
```

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Did you see this warning in the issue template?

> Without proving the bug is in tsx via minimal reproduction, your issue will be closed without response.

Happy to re-open once a reproduction is provided.

**Comment by ivodolenc** [comment]
Okay, this is a friendly bug report if you don't want to test it that's fine with me. 

Try the simple instructions I have provided. Simply add `${configDir}` in any project to the `tsconfig.json` file and try to run the `tsx` build.

**Comment by ivodolenc** [comment]
I'm not asking you for anything, least of all to do something for free. Feel free to ignore this report. Cheers!
