### ISSUE TITLE
Broken dynamic imports.

### ISSUE THREAD

**Issue by psznm** [privatenumber/tsx#651]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/psznm/tsx-dynamic-import-bug-repro

### Problem & expected behavior (under 200 words)

As described in README of the repro repository. Dynamic imports seem to not respect relative paths and always resolve to the first loaded module with same "name" even if it is actually different modules in different directories.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by psznm** [comment]
The same actually happens when I replace the dynamic imports with static imports.

**Comment by privatenumber** [comment]
Strange bug! Nice find, and thanks for the minimal reproduction

**Comment by privatenumber** [comment]
This issue is now resolved in [v4.19.1](https://github.com/privatenumber/tsx/releases/tag/v4.19.1).

If you're able to, [your sponsorship](https://github.com/sponsors/privatenumber) would be very much appreciated.
