### ISSUE TITLE
Consider deprecating `@esbuild-kit/esm-loader`

### ISSUE THREAD

**Issue by benmccann** [privatenumber/tsx#658]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://www.npmjs.com/package/@esbuild-kit/esm-loader

### Problem & expected behavior (under 200 words)

https://www.npmjs.com/package/@esbuild-kit/esm-loader doesn't show that it's deprecated nor does npm. It's quite hard to figure out and you only see that it's unmaintained when visiting https://github.com/esbuild-kit/esm-loader. Please consider deprecating it via npm to help people move

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Deprecated:
- https://www.npmjs.com/package/@esbuild-kit/esm-loader
- https://www.npmjs.com/package/@esbuild-kit/cjs-loader
- https://www.npmjs.com/package/@esbuild-kit/core-utils

Thanks for the reminder!
