### ISSUE TITLE
`--env-file` reads commented-out lines of file!

### ISSUE THREAD

**Issue by zsiegel92** [privatenumber/tsx#662]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/zsiegel92/tsx_env_var_bug_mwe

### Problem & expected behavior (under 200 words)

The `.env` file in the MWE repo looks like this:

```sh
ENV_VAR=right # comment after
# ENV_VAR=wrong
```

Using `npx tsx --env-file .env test.ts`, the commented-out wrong variable is set during execution rather than the correct one. The conditions for this are:
- the correct one has a comment after the line where it's defined
- the wrong one appears below the right one

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
This is not a tsx bug—it doesn't implement this feature. All unrecognized flags are just relayed to the underlying `node` command to handle.

I also can't reproduce with the latest Node:
```
$ tsx --env-file=.env ./test.ts
right
$ node -v
v22.9.0
```

But you're likely encountering https://github.com/nodejs/node/issues/52084
