### ISSUE TITLE
Support type checking

### ISSUE THREAD

**Issue by bisubus** [privatenumber/tsx#671]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/bisubus/node-app-template/blob/39de183f651b02b917a02d5bd8ad9d5c433e8da1/package.json

### Problem & expected behavior (under 200 words)

This is a feature request rather than a bug. I'm interested in collaborating on it

This has already been addressed with https://github.com/privatenumber/tsx/issues/121 but no proper reasoning was provided. The missing point is that tsx is advertised as a replacement for ts-node (which is abandoned) but provides no feature parity. ts-node provides type checks. The suggested `tsc --noEmit` workaround isn't convenient for regular run and cannot be effectively used for interactive and watch modes.

Here is [an example](https://github.com/bisubus/node-app-template/blob/39de183f651b02b917a02d5bd8ad9d5c433e8da1/package.json) of a possible workaround with watch mode:

```json
  "scripts": {
    "check": "tsc --noEmit",
    "no-check:watch": "tsx watch --clear-screen=false --import=./env.ts src/index.ts",
    "watch": "run-p \"check -- --watch\" no-check:watch",
  },
```

The problem is that it cannot prevent a rebuild on type errors. Since tsx cli wasn't written to be extendable, this would require to fully discard watch feature and do this from scratch, e.g. with nodemon. And there is no workaround for interactive mode.

I assume the approach to optional type checking would be to rely on the existence of `tsc` without introducing `typescript` as a direct dependency, or import `typescript` optional dependency to process repl lines, both for global and local use

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Thanks for the issue but this is a bug tracker. Please file your feature request in the sponsors-only development repo.
