### ISSUE TITLE
TypeError: ClassName is not a constructor

### ISSUE THREAD

**Issue by chanakya-svt** [privatenumber/tsx#674]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/chanakya-svt/crd2pulumi-tsx-repro

### Problem & expected behavior (under 200 words)

The reproduction repo has a readme with the error, but in short when importing and invoking a class I am receiving the following error:
```
/apps/crds/index.ts:3
new certManagerIssuers.cert_manager.v1.Issuer(
  ^
TypeError: import_src.certManagerIssuers.cert_manager.v1.Issuer is not a constructor
```

Versions: 

- tsx v4.19.2
- node v22.11.0
- typescript v5.6.3

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Sorry but your reproduction is not minimal. I'm sure you don't need all those dependencies. Please minimize it down to under 5 files.

Happy to reopen the issue once updated.

**Comment by chanakya-svt** [comment]
@privatenumber 

Thank you for your quick response regarding the issue. The reproduction repository is minimal, containing just one file (apps/crds/index.ts), which serves as the main program.

All other files within libs/custom-resource-definitions are automatically generated by the crd2pulumi tool. Each of these files includes a warning comment at the top, like the one below:
```
// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
```
As a result, the files in `libs/custom-resource-definitions` should be treated as external libraries, and no modifications can be made to them. This means that `apps/crds/index.ts` is the only file that can be modified along with nx(project.json), pulumi(Pulumi.yaml) and typescript(tsconfig.*.json) metadata files.

**Comment by privatenumber** [comment]
- Could you please remove Nx, Pulumi, and Prettier?
- There seem to be quite a few files in `libs/custom-resource-definitions/src/cert-manager` for it to be considered a minimal reproduction.
- Please remove any files or code that are not essential for reproducing the error—delete as much as possible.
