### ISSUE TITLE
TSX is not formatting template string variables on .env file

### ISSUE THREAD

**Issue by rajatsandeepsen** [privatenumber/tsx#681]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/drizzle-team/drizzle-orm/issues/3687

### Here is an example what happening in TSX

```ts
// code.js
console.log("DATABASE_URL:", process.env.DATABASE_URL)
console.log("PASSWORD:", process.env.PASSWORD)
```

```env
# .env file
PASSWORD="1234567890"
DATABASE_URL="postgresql://postgres:${PASSWORD}@localhost:5432/db"
```

```bash
#  run the javascript code with .env file attached
tsx  --env-file=./.env ./code.js
```

```bash
# console output

DATABASE_URL: postgresql://postgres:${PASSWORD}@localhost:5432/db
PASSWORD: 1234567890
```

### Same code running in Bun.js

```bash
#  .env file is automatically attached
bun run ./code.js
```

```bash
# console output

DATABASE_URL: postgresql://postgres:1234567890@localhost:5432/db
PASSWORD: 1234567890
```

Compared to bun.js or docker-compose perspective, this what should be happening. 
Maybe due to that library or parsing method for reading env, i think formatting template string variables isn't implemented on TSX (yet)

That's why people is having this `Error: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing` issue [on supabase](https://github.com/supabase/supabase/issues/21690#issuecomment-1988586600)

Because [drizzle-kit cli](https://github.com/drizzle-team/drizzle-orm/blob/main/drizzle-kit) is using TSX for reading `drizzle.config.ts`

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment]
Thanks for the issue, but the `--env-file` flag is a Node feature, and tsx doesn't contain any code for it (all unrecognized flags are passed down to Node). You'll want to file your report there.
